---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /v1/auth
            backend:
              serviceName: auth
              servicePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
  namespace: apps
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: moov.io/auth:v0.1.0-dev
        imagePullPolicy: Always
        name: auth
        ports:
          - containerPort: 8080
            name: htp
            protocol: TCP
      restartPolicy: Always
      # serviceAccount: auth
      # serviceAccountName: auth

---
