---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: proxy
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy
  namespace: apps
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
              weight: 1
      containers:
        # This image is built from the api repository
      - image: moov/localdevproxy:latest
        imagePullPolicy: Always
        name: proxy
        args:
          - -debug
          - -http.addr=:9000
        ports:
          - containerPort: 9000
            name: http
            protocol: TCP
        resources:
          limits:
            cpu: 0.1
            memory: 50Mi
          requests:
            cpu: 25m
            memory: 10Mi
        readinessProbe:
          httpGet:
            path: /ping
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always

---
