sudo: required

services:
  - docker

language: go

os:
  - linux
  - osx
go:
  - 1.13.x

before_install:
  - mkdir -p ~/bin/
  # Terraform
  # - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  # - unzip -d ~/bin/ terraform.zip
  # - mkdir -p ~/.google/ && touch ~/.google/credentials.json
  # adamdecaf/promtool-configmap
  - wget -O prometheus.tar.gz https://github.com/prometheus/prometheus/releases/download/v2.15.2/prometheus-2.15.2.darwin-amd64.tar.gz
  - tar xf prometheus.tar.gz && cp -r ./prometheus-*/promtool ~/bin/promtool
  # promtool-configmap
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O ~/bin/promtool-configmap https://github.com/adamdecaf/promtool-configmap/releases/download/v0.3.0/promtool-configmap-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O ~/bin/promtool-configmap https://github.com/adamdecaf/promtool-configmap/releases/download/v0.3.0/promtool-configmap-macos; fi
  - chmod +x ~/bin/promtool-configmap
  # gitleaks
  - go get github.com/zricethezav/gitleaks
  - go get ./...

script:
  - gitleaks --repo-path=$(pwd) --redact -v
  # Terraform
  # cd envs/sbx && terraform init && terraform validate
  # Prometheus
  - promtool-configmap --version
  - promtool-configmap envs/prod/infra/14-prometheus.yml
  - promtool-configmap envs/prod/infra/14-prometheus-rules.yml
  # Run infra tests
  - make test
  - CGO_ENABLED=0 go test ./...

notifications:
  slack:
    secure: MYljviqsTwifTAy8gEfEYhu37RaYWPTfS3LYXa0gz1tylVszy7D5XgSEjlZfZaDhWOTMl2paEhcM+Y+1WPHT+jlPjNu1K2k4GyEwSSFWaSA4O+G9msHP9P6xPStQHQUzJxH3YwaFWZCvq6TXcTiWiU0BFbj8wFXCD2ELrQwWcdRDFOY6hPijecnwdsXxEEF/fknsOO6/YMIIP7wNPpm+vFWxwPXsl3lyXOTwOyffz2SDkpFEoKw+qnP4xPj4GhufqfI5Zmf6IDWs17srVlZ9DHsUAjJAdSfr9SpwsA+RVYZnzlkB/YGT5PDksHZmMFZuSQSuPRKPCGfYX4ps1/tQR/Kko2fpnPUfT+yyCPkVbcvEw26R+KfKTOAwf6q4rr0a9kSdLxg42baOgS6/XUkkZR86RJ1tCmsN/zkAZllX8ydxTZC4aTFBcLlsbSXd+61btmQoI1KR8DexAFWg8fXHS/UgT47uk1K5+SssOAu8Tu39by/Yk8kxoye9oaka1p78tGmGyMrxp2QgNUyZfWsodUxol74Uzwskery9FrdxjxgIMjUIIfDcGytismKsFvpikXTJJ8x1sxnC53bhsRVFg0zCggpt5hjKnlXKF/TokA6Be8SZ8C+c7UtTZg9/HH7AhRgAiP1+V8hr+cVFcP1gG2++R79mC0Q1WFHbdgbmGqs=
