sudo: false

language: go
os:
  - linux
  - osx
go:
  - 1.11

osx_image: xcode9.1

before_install:
  # Terraform
  # - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  # - mkdir -p ~/bin/ && unzip -d ~/bin/ terraform.zip
  # - mkdir -p ~/.google/ && touch ~/.google/credentials.json
  # adamdecaf/promtool-configmap
  - go get github.com/prometheus/prometheus/cmd/promtool
  - go get -u github.com/adamdecaf/promtool-configmap
script:
  # Terraform
  # cd envs/sbx && terraform init && terraform validate
  # Prometheus
  - promtool-configmap --version
  - promtool-configmap envs/sbx/infra/14-prometheus.yml
