sudo: required

services:
  - docker

language: go

os:
  - linux
  - osx
go:
  - 1.13.x

before_install:
  - mkdir -p ~/bin/
  # Terraform
  # - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  # - unzip -d ~/bin/ terraform.zip
  # - mkdir -p ~/.google/ && touch ~/.google/credentials.json
  # adamdecaf/promtool-configmap
  - wget -O prometheus.tar.gz https://github.com/prometheus/prometheus/releases/download/v2.15.2/prometheus-2.15.2.darwin-amd64.tar.gz
  - tar xf prometheus.tar.gz && cp -r ./prometheus-*/promtool ~/bin/promtool
  # promtool-configmap
  - wget -O ~/bin/promtool-configmap https://github.com/adamdecaf/promtool-configmap/releases/download/v0.3.0/promtool-configmap-linux
  - chmod +x ~/bin/promtool-configmap
  # gitleaks
  - go get github.com/zricethezav/gitleaks
  - go get ./...

script:
  - gitleaks --repo-path=$(pwd) --redact -v
  # Terraform
  # cd envs/sbx && terraform init && terraform validate
  # Prometheus
  - promtool-configmap --version
  - promtool-configmap envs/prod/infra/14-prometheus.yml
  - promtool-configmap envs/prod/infra/14-prometheus-rules.yml
  # Run infra tests
  - make test
  - CGO_ENABLED=0 go test ./...
