sudo: required
services:
  - docker
language: go
os:
  - linux
  - osx
go:
  - 1.12.x

osx_image: xcode9.1

before_install:
  # Terraform
  # - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  # - mkdir -p ~/bin/ && unzip -d ~/bin/ terraform.zip
  # - mkdir -p ~/.google/ && touch ~/.google/credentials.json
  # adamdecaf/promtool-configmap
  - go get github.com/prometheus/prometheus/cmd/promtool
  - go get -u github.com/adamdecaf/promtool-configmap
  - go get github.com/zricethezav/gitleaks
  # Setup kubeval
  - wget https://github.com/instrumenta/kubeval/releases/download/0.10.0/kubeval-linux-amd64.tar.gz
  - tar -xf kubeval-linux-amd64.tar.gz && chmod +x ./kubeval
script:
  - gitleaks --repo-path=$(pwd)
  # Terraform
  # cd envs/sbx && terraform init && terraform validate
  # Prometheus
  - promtool-configmap --version
  - promtool-configmap envs/prod/infra/14-prometheus.yml
  - promtool-configmap envs/prod/infra/14-prometheus-rules.yml
  # Run infra tests
  - make test
  - CGO_ENABLED=0 go test ./...
  # kubeval
  - find lib/* -type f -name *.yml | grep -v blackbox | xargs -n1 -I {} ./kubeval $(pwd)/'{}' --strict
