version: '3'
services:
  traefik:
    image: traefik:v1.7
    command: --api --docker --logLevel="DEBUG" # --traefikLog.format="json" --accessLog.format="json"
    ports:
      - "80:80"     # proxy
      - "8080:8080" # api/web UI
    volumes:
      # required for docker events
      - /var/run/docker.sock:/var/run/docker.sock
  auth:
    image: moov.io/auth:v0.1.0-dev
    labels:
      - 'traefik.frontend.rule=Path:/v1/auth'
      - 'traefik.frontend.rule=ReplacePathRegex: ^/v1/auth/(.*) /$$1'
      # - "traefik.frontend.rule=Host:api.moov.io" # /v1/auth
      # - "traefik.backend.circuitbreaker.expression"
      # - "traefik.backend.healthcheck.path=/health"
      # - "traefik.backend.healthcheck.port=8080"
    ports:
      - "10001:8080"
      - "10002:9090"
  ach:
    image: moov.io/ach:v0.3.0-dev
    ports:
      - "10003:8080"
      - "10004:9090"
    labels:
      - 'traefik.frontend.rule=Path:/v1/ach'
      - 'traefik.frontend.rule=ReplacePathRegex: ^/v1/ach/(.*)/? /$$1'
      # - "traefik.frontend.rule=Host:api.moov.io"
      # forward auth to /authorize
  # prometheus:
  #   image: prom/prometheus:v2.4.0
  #   volumes:
  #     - /home/adam/code/src/github.com/moov-io/infra/deployments/traefik-spike/prometheus/:/etc/prometheus/
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   ports:
  #     - 9090:9090
  #   labels:
  #     - "traefik.frontend.rule=Host:infra.moov.io"


# /token?grant_type=client_credentials&client_id=000000&client_secret=999999&scope=read
