---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: sales
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: gcr.io/maynard-io-public/kubernetes-cloud-mysql-backup:v2.2.0
            name: mysql-backup
            imagePullPolicy: Always
            env:
              - name: GCP_GCLOUD_AUTH
                valueFrom:
                   secretKeyRef:
                     name: mysql-secrets
                     key: gcp_gcloud_auth
              - name: BACKUP_PROVIDER
                value: "gcp"
              - name: GCP_BUCKET_NAME
                value: "moov-production-mysql-backups"
              - name: GCP_BUCKET_BACKUP_PATH
                value: "/sales/mysql"
              - name: TARGET_DATABASE_HOST
                value: "mysql.sales.svc.cluster.local"
              - name: TARGET_DATABASE_PORT
                value: "3306"
              - name: TARGET_DATABASE_NAMES
                valueFrom:
                   secretKeyRef:
                     name: mysql-secrets
                     key: database
              - name: TARGET_DATABASE_USER
                valueFrom:
                   secretKeyRef:
                     name: mysql-secrets
                     key: username
              - name: TARGET_DATABASE_PASSWORD
                valueFrom:
                   secretKeyRef:
                     name: mysql-secrets
                     key: password
              - name: BACKUP_TIMESTAMP
                value: "_%Y_%m_%d"
              - name: SLACK_ENABLED
                value: "true"
              - name: SLACK_CHANNEL
                value: "#alerts"
              - name: SLACK_WEBHOOK_URL
                valueFrom:
                   secretKeyRef:
                     name: mysql-secrets
                     key: slack_webhook_url
          restartPolicy: OnFailure
---
